version: '3.9'
services:
 jenkins:
  user: root
  build: .
  image: "jenkinsci/blueocean:1.23.1"
  restart: unless-stopped
  hostname: jenkins
  ports:
   - "8080:8080"
  volumes:
   - ./jenkins_home:/var/jenkins_home
  env_file: .env
